### ISSUE TITLE
Vision Python Code

### ISSUE THREAD

**Issue by Purgso** [Team818SteelArmadillos/2020InfiniteRecharge#12]
Vertical angle calculation isn't correct
  * Frame.shape[0] gives the image height in pixels
  * Frame.shape[1] gives the image width in pixels
  * You can either modify the existing code, write your own angle calculation code, or follow the limelight documentation
      * http://docs.limelightvision.io/en/latest/theory.html#from-pixels-to-angles

Horizontal and vertical angles should be 0 if no target is found

**Comment by Mj2758** [comment]
@Purgso whats the frame of our camera for this year?
