### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by Purgso** [Team818SteelArmadillos/2020InfiniteRecharge#22]
1 motor using a Victor SPX
2 pistons to extend and retract the intake mechanism
Add a function for setting motor power
Add a function for extending and retracting the intake
  * Take a boolean as a parameter.  If true, extend the intake.  If false, retract the intake

logData - put values in smart dashboard
  * Motor power
  * If the intake is extended or retracted

**Comment by hershey1027** [comment]
Done!
