### ISSUE TITLE
Tank Drive Command

### ISSUE THREAD

**Issue by Purgso** [Team818SteelArmadillos/2020InfiniteRecharge#32]

**Comment by Purgso** [comment]
Tank drive will have 2 shifting modes.  Make a boolean constant to decide which is active.
Manual shifting - switch gear when Right Joystick button 2 is pressed.
Auto shifting - If robot is in low gear and speed is > 5.5 ft/s, go to high gear.  If robot is in high gear and speed is < 4 ft/s, go to low gear.

**Comment by JTran933** [comment]
Done. Closing Issue
