### ISSUE TITLE
WoF Subsystem

### ISSUE THREAD

**Issue by Purgso** [Team818SteelArmadillos/2020InfiniteRecharge#9]
Change Motor Controller to Victor SPX
Log GameData to Smart Dashboard when getGameData() is called
Do red and yellow need to be swapped in getGameData()?
Add logData function to log values in Smart Dashboard:
  * Raw R, G, and B values from sensor
  * Detected color
  * Motor power

**Comment by JohnSchultz0403** [comment]
We don't think it is necessary to put motor power in the Smart Dashboard. There are better ways of seeing if it is working that don't involve taking a space in the Dashboard. It is also unlikely to brown out as it will always only be running by itself.

**Comment by ssmazzola** [comment]
I am confused about "Do red and yellow need to be swapped in getGameData()?" From what I can tell it is fine.
